# Generated by Django 4.2.3 on 2023-07-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ffirst_name',
            new_name='first_name',
        ),
    ]
